backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/uploads"

collections:
  - name: "posts"
  label: "Post"
  folder: "content/posts"
  slug: "{{slug}}"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "body", name: "body", widget: "markdown"}
